# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - candlestick-screener

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://candlestickscreenerregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4d395d8ef0754d499cd722740bad2c53 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_014a82e656864783a9cb71cff2682925 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: candlestickscreenerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4d395d8ef0754d499cd722740bad2c53 }}/candlestick-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'candlestick-screener'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f1b81b169d2344a7837b2516e72234a2 }}
        images: 'candlestickscreenerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4d395d8ef0754d499cd722740bad2c53 }}/candlestick-app:${{ github.sha }}'